### ISSUE TITLE
Theme handling with css variables

### ISSUE THREAD

**Issue by xinaesthete** [Taylor-CCB-Group/MDV#6]
There are quite a few parts of the code where element styling is done by setting style properties of individual elements in js - obviously makes sense for things like positioning of panels, less ideal elsewhere. So it goes.

At the risk of fixing things that aren't particularly broken, I've been fiddling with some changes to the way the theme selection works, using either a dark or light class applied to the document root, and getting rid of most of the theme setting JS code:

```js
class ChartManager {
  setTheme(theme) {
    this.theme = theme;
    document.getElementsByTagName('html')[0].className = theme;
  }
}
```

```css
.Dark {
  --text_color: white;
}
.Light {
  --text_color: black;
}
.ciview-chart-content {
  color: var(--text_color);
}

/*
.table-dark-mode .slick-row.odd{
  background:#303030;
}
*/

.Dark .slick-row.odd{
  background:#303030;
}
```

This all seems to be working fine, at least in the basic example and with any of the views I've tried (tables seemed to be the only thing which needed some extra attention)... I suppose there could be ways in which it was subtly incompatible with things I've failed to consider, but I think I can see reasonably clearly what's going on, so I think I'll go ahead and commit my changes (not going to bother with a separate branch etc, seems overkill here).
